instrumentation:
    root: src
    include-all-sources: true
    es-modules: false
reporting:
    print: summary
    reports:
        - lcov
        - html
    dir: ./build/coverage
    watermarks:
        statements: [50, 85]
        lines: [50, 85]
        functions: [50, 85]
        branches: [50, 85]
